// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/isr'. DO NOT EDIT.

package idensyra

import (
	"github.com/HazelnutParadise/insyra/isr"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/isr/isr"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Name": reflect.ValueOf(isr.Name),

		// type definitions
		"CSV":         reflect.ValueOf((*isr.CSV)(nil)),
		"CSV_inOpts":  reflect.ValueOf((*isr.CSV_inOpts)(nil)),
		"CSV_outOpts": reflect.ValueOf((*isr.CSV_outOpts)(nil)),
		"Col":         reflect.ValueOf((*isr.Col)(nil)),
		"DL":          reflect.ValueOf((*isr.DL)(nil)),
		"DLs":         reflect.ValueOf((*isr.DLs)(nil)),
		"DT":          reflect.ValueOf((*isr.DT)(nil)),
		"JSON":        reflect.ValueOf((*isr.JSON)(nil)),
		"Row":         reflect.ValueOf((*isr.Row)(nil)),
	}
}
