// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/datafetch'. DO NOT EDIT.

package idensyra

import (
	"github.com/HazelnutParadise/insyra/datafetch"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/datafetch/datafetch"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GoogleMapsStores":    reflect.ValueOf(datafetch.GoogleMapsStores),
		"SortByHighestRating": reflect.ValueOf(datafetch.SortByHighestRating),
		"SortByLowestRating":  reflect.ValueOf(datafetch.SortByLowestRating),
		"SortByNewest":        reflect.ValueOf(datafetch.SortByNewest),
		"SortByRelevance":     reflect.ValueOf(datafetch.SortByRelevance),

		// type definitions
		"GoogleMapsStoreData":                   reflect.ValueOf((*datafetch.GoogleMapsStoreData)(nil)),
		"GoogleMapsStoreReview":                 reflect.ValueOf((*datafetch.GoogleMapsStoreReview)(nil)),
		"GoogleMapsStoreReviewSortBy":           reflect.ValueOf((*datafetch.GoogleMapsStoreReviewSortBy)(nil)),
		"GoogleMapsStoreReviews":                reflect.ValueOf((*datafetch.GoogleMapsStoreReviews)(nil)),
		"GoogleMapsStoreReviewsFetchingOptions": reflect.ValueOf((*datafetch.GoogleMapsStoreReviewsFetchingOptions)(nil)),
	}
}
