// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/parallel'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/parallel"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/parallel/parallel"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GroupUp": reflect.ValueOf(parallel.GroupUp),

		// type definitions
		"ParallelGroup": reflect.ValueOf((*parallel.ParallelGroup)(nil)),
	}
}
