// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/stats'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/stats"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/stats/stats"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BartlettSphericity":        reflect.ValueOf(stats.BartlettSphericity),
		"BartlettTest":              reflect.ValueOf(stats.BartlettTest),
		"CalculateMoment":           reflect.ValueOf(stats.CalculateMoment),
		"ChiSquareGoodnessOfFit":    reflect.ValueOf(stats.ChiSquareGoodnessOfFit),
		"ChiSquareIndependenceTest": reflect.ValueOf(stats.ChiSquareIndependenceTest),
		"Correlation":               reflect.ValueOf(stats.Correlation),
		"CorrelationAnalysis":       reflect.ValueOf(stats.CorrelationAnalysis),
		"CorrelationMatrix":         reflect.ValueOf(stats.CorrelationMatrix),
		"Covariance":                reflect.ValueOf(stats.Covariance),
		"Diag":                      reflect.ValueOf(stats.Diag),
		"ExponentialRegression":     reflect.ValueOf(stats.ExponentialRegression),
		"FTestForNestedModels":      reflect.ValueOf(stats.FTestForNestedModels),
		"FTestForRegression":        reflect.ValueOf(stats.FTestForRegression),
		"FTestForVarianceEquality":  reflect.ValueOf(stats.FTestForVarianceEquality),
		"Greater":                   reflect.ValueOf(stats.Greater),
		"KendallCorrelation":        reflect.ValueOf(stats.KendallCorrelation),
		"Kurtosis":                  reflect.ValueOf(stats.Kurtosis),
		"KurtosisAdjusted":          reflect.ValueOf(stats.KurtosisAdjusted),
		"KurtosisBiasAdjusted":      reflect.ValueOf(stats.KurtosisBiasAdjusted),
		"KurtosisG2":                reflect.ValueOf(stats.KurtosisG2),
		"Less":                      reflect.ValueOf(stats.Less),
		"LeveneTest":                reflect.ValueOf(stats.LeveneTest),
		"LinearRegression":          reflect.ValueOf(stats.LinearRegression),
		"LogarithmicRegression":     reflect.ValueOf(stats.LogarithmicRegression),
		"OneWayANOVA":               reflect.ValueOf(stats.OneWayANOVA),
		"PCA":                       reflect.ValueOf(stats.PCA),
		"PairedTTest":               reflect.ValueOf(stats.PairedTTest),
		"PearsonCorrelation":        reflect.ValueOf(stats.PearsonCorrelation),
		"PolynomialRegression":      reflect.ValueOf(stats.PolynomialRegression),
		"RepeatedMeasuresANOVA":     reflect.ValueOf(stats.RepeatedMeasuresANOVA),
		"SingleSampleTTest":         reflect.ValueOf(stats.SingleSampleTTest),
		"SingleSampleZTest":         reflect.ValueOf(stats.SingleSampleZTest),
		"Skewness":                  reflect.ValueOf(stats.Skewness),
		"SkewnessAdjusted":          reflect.ValueOf(stats.SkewnessAdjusted),
		"SkewnessBiasAdjusted":      reflect.ValueOf(stats.SkewnessBiasAdjusted),
		"SkewnessG1":                reflect.ValueOf(stats.SkewnessG1),
		"SpearmanCorrelation":       reflect.ValueOf(stats.SpearmanCorrelation),
		"TwoSampleTTest":            reflect.ValueOf(stats.TwoSampleTTest),
		"TwoSampleZTest":            reflect.ValueOf(stats.TwoSampleZTest),
		"TwoSided":                  reflect.ValueOf(stats.TwoSided),
		"TwoWayANOVA":               reflect.ValueOf(stats.TwoWayANOVA),

		// type definitions
		"ANOVAResultComponent":        reflect.ValueOf((*stats.ANOVAResultComponent)(nil)),
		"AlternativeHypothesis":       reflect.ValueOf((*stats.AlternativeHypothesis)(nil)),
		"ChiSquareTestResult":         reflect.ValueOf((*stats.ChiSquareTestResult)(nil)),
		"CorrelationMethod":           reflect.ValueOf((*stats.CorrelationMethod)(nil)),
		"CorrelationResult":           reflect.ValueOf((*stats.CorrelationResult)(nil)),
		"EffectSizeEntry":             reflect.ValueOf((*stats.EffectSizeEntry)(nil)),
		"ExponentialRegressionResult": reflect.ValueOf((*stats.ExponentialRegressionResult)(nil)),
		"FTestResult":                 reflect.ValueOf((*stats.FTestResult)(nil)),
		"KurtosisMethod":              reflect.ValueOf((*stats.KurtosisMethod)(nil)),
		"LinearRegressionResult":      reflect.ValueOf((*stats.LinearRegressionResult)(nil)),
		"LogarithmicRegressionResult": reflect.ValueOf((*stats.LogarithmicRegressionResult)(nil)),
		"OneWayANOVAResult":           reflect.ValueOf((*stats.OneWayANOVAResult)(nil)),
		"PCAResult":                   reflect.ValueOf((*stats.PCAResult)(nil)),
		"PolynomialRegressionResult":  reflect.ValueOf((*stats.PolynomialRegressionResult)(nil)),
		"RepeatedMeasuresANOVAResult": reflect.ValueOf((*stats.RepeatedMeasuresANOVAResult)(nil)),
		"SkewnessMethod":              reflect.ValueOf((*stats.SkewnessMethod)(nil)),
		"TTestResult":                 reflect.ValueOf((*stats.TTestResult)(nil)),
		"TwoWayANOVAResult":           reflect.ValueOf((*stats.TwoWayANOVAResult)(nil)),
		"ZTestResult":                 reflect.ValueOf((*stats.ZTestResult)(nil)),
	}
}
