// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/isr'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/isr"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/isr/isr"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DL":   reflect.ValueOf(&isr.DL).Elem(),
		"DT":   reflect.ValueOf(&isr.DT).Elem(),
		"Name": reflect.ValueOf(isr.Name),

		// type definitions
		"CSV":          reflect.ValueOf((*isr.CSV)(nil)),
		"CSV_inOpts":   reflect.ValueOf((*isr.CSV_inOpts)(nil)),
		"CSV_outOpts":  reflect.ValueOf((*isr.CSV_outOpts)(nil)),
		"Col":          reflect.ValueOf((*isr.Col)(nil)),
		"Cols":         reflect.ValueOf((*isr.Cols)(nil)),
		"DLs":          reflect.ValueOf((*isr.DLs)(nil)),
		"Excel":        reflect.ValueOf((*isr.Excel)(nil)),
		"Excel_inOpts": reflect.ValueOf((*isr.Excel_inOpts)(nil)),
		"JSON":         reflect.ValueOf((*isr.JSON)(nil)),
		"Row":          reflect.ValueOf((*isr.Row)(nil)),
		"Rows":         reflect.ValueOf((*isr.Rows)(nil)),
	}
}
