// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/py'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/py"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/py/py"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"PipInstall":     reflect.ValueOf(py.PipInstall),
		"PipUninstall":   reflect.ValueOf(py.PipUninstall),
		"ReinstallPyEnv": reflect.ValueOf(py.ReinstallPyEnv),
		"RunCode":        reflect.ValueOf(py.RunCode),
		"RunCodef":       reflect.ValueOf(py.RunCodef),
		"RunFile":        reflect.ValueOf(py.RunFile),
		"RunFilef":       reflect.ValueOf(py.RunFilef),
	}
}
