// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/csvxl'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/csvxl"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/csvxl/csvxl"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AppendCsvToExcel":  reflect.ValueOf(csvxl.AppendCsvToExcel),
		"Auto":              reflect.ValueOf(constant.MakeFromLiteral("\"auto\"", token.STRING, 0)),
		"Big5":              reflect.ValueOf(constant.MakeFromLiteral("\"big5\"", token.STRING, 0)),
		"CsvToExcel":        reflect.ValueOf(csvxl.CsvToExcel),
		"EachCsvToOneExcel": reflect.ValueOf(csvxl.EachCsvToOneExcel),
		"EachExcelToCsv":    reflect.ValueOf(csvxl.EachExcelToCsv),
		"ExcelToCsv":        reflect.ValueOf(csvxl.ExcelToCsv),
		"ReadCsvToString":   reflect.ValueOf(csvxl.ReadCsvToString),
		"UTF8":              reflect.ValueOf(constant.MakeFromLiteral("\"utf-8\"", token.STRING, 0)),
	}
}
