// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/lp'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/lp"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/lp/lp"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"SolveFromFile": reflect.ValueOf(lp.SolveFromFile),
		"SolveModel":    reflect.ValueOf(lp.SolveModel),
	}
}
