// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/mkt'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/mkt"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/mkt/mkt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CAI":                   reflect.ValueOf(&mkt.CAI).Elem(),
		"CustomerActivityIndex": reflect.ValueOf(mkt.CustomerActivityIndex),
		"RFM":                   reflect.ValueOf(mkt.RFM),
		"TimeScaleDaily":        reflect.ValueOf(mkt.TimeScaleDaily),
		"TimeScaleHourly":       reflect.ValueOf(mkt.TimeScaleHourly),
		"TimeScaleMonthly":      reflect.ValueOf(mkt.TimeScaleMonthly),
		"TimeScaleWeekly":       reflect.ValueOf(mkt.TimeScaleWeekly),
		"TimeScaleYearly":       reflect.ValueOf(mkt.TimeScaleYearly),

		// type definitions
		"CAIConfig": reflect.ValueOf((*mkt.CAIConfig)(nil)),
		"RFMConfig": reflect.ValueOf((*mkt.RFMConfig)(nil)),
		"TimeScale": reflect.ValueOf((*mkt.TimeScale)(nil)),
	}
}
