// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/parquet'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/parquet"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/parquet/parquet"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ApplyCCL":      reflect.ValueOf(parquet.ApplyCCL),
		"FilterWithCCL": reflect.ValueOf(parquet.FilterWithCCL),
		"Inspect":       reflect.ValueOf(parquet.Inspect),
		"Read":          reflect.ValueOf(parquet.Read),
		"ReadColumn":    reflect.ValueOf(parquet.ReadColumn),
		"Stream":        reflect.ValueOf(parquet.Stream),
		"Write":         reflect.ValueOf(parquet.Write),

		// type definitions
		"ColumnInfo":        reflect.ValueOf((*parquet.ColumnInfo)(nil)),
		"FileInfo":          reflect.ValueOf((*parquet.FileInfo)(nil)),
		"ReadColumnOptions": reflect.ValueOf((*parquet.ReadColumnOptions)(nil)),
		"ReadOptions":       reflect.ValueOf((*parquet.ReadOptions)(nil)),
		"RowGroupInfo":      reflect.ValueOf((*parquet.RowGroupInfo)(nil)),
	}
}
