// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra"
	"go/constant"
	"go/token"
	"gorm.io/gorm"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/insyra"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CalcColIndex":                  reflect.ValueOf(insyra.CalcColIndex),
		"ClearErrors":                   reflect.ValueOf(insyra.ClearErrors),
		"Config":                        reflect.ValueOf(&insyra.Config).Elem(),
		"ConvertLongDataToWide":         reflect.ValueOf(insyra.ConvertLongDataToWide),
		"DetectEncoding":                reflect.ValueOf(insyra.DetectEncoding),
		"ErrPoppingModeFIFO":            reflect.ValueOf(insyra.ErrPoppingModeFIFO),
		"ErrPoppingModeLIFO":            reflect.ValueOf(insyra.ErrPoppingModeLIFO),
		"GetAllErrors":                  reflect.ValueOf(insyra.GetAllErrors),
		"GetErrorCount":                 reflect.ValueOf(insyra.GetErrorCount),
		"GetErrorsByLevel":              reflect.ValueOf(insyra.GetErrorsByLevel),
		"GetErrorsByPackage":            reflect.ValueOf(insyra.GetErrorsByPackage),
		"HasError":                      reflect.ValueOf(insyra.HasError),
		"HasErrorAboveLevel":            reflect.ValueOf(insyra.HasErrorAboveLevel),
		"IsNumeric":                     reflect.ValueOf(insyra.IsNumeric),
		"LogDebug":                      reflect.ValueOf(insyra.LogDebug),
		"LogFatal":                      reflect.ValueOf(insyra.LogFatal),
		"LogInfo":                       reflect.ValueOf(insyra.LogInfo),
		"LogLevelDebug":                 reflect.ValueOf(insyra.LogLevelDebug),
		"LogLevelFatal":                 reflect.ValueOf(insyra.LogLevelFatal),
		"LogLevelInfo":                  reflect.ValueOf(insyra.LogLevelInfo),
		"LogLevelWarning":               reflect.ValueOf(insyra.LogLevelWarning),
		"LogWarning":                    reflect.ValueOf(insyra.LogWarning),
		"MergeDirectionHorizontal":      reflect.ValueOf(insyra.MergeDirectionHorizontal),
		"MergeDirectionVertical":        reflect.ValueOf(insyra.MergeDirectionVertical),
		"MergeModeInner":                reflect.ValueOf(insyra.MergeModeInner),
		"MergeModeLeft":                 reflect.ValueOf(insyra.MergeModeLeft),
		"MergeModeOuter":                reflect.ValueOf(insyra.MergeModeOuter),
		"MergeModeRight":                reflect.ValueOf(insyra.MergeModeRight),
		"NewDataList":                   reflect.ValueOf(insyra.NewDataList),
		"NewDataTable":                  reflect.ValueOf(insyra.NewDataTable),
		"ParseColIndex":                 reflect.ValueOf(insyra.ParseColIndex),
		"PeekError":                     reflect.ValueOf(insyra.PeekError),
		"PopAllErrors":                  reflect.ValueOf(insyra.PopAllErrors),
		"PopError":                      reflect.ValueOf(insyra.PopError),
		"PopErrorAndCallback":           reflect.ValueOf(insyra.PopErrorAndCallback),
		"PopErrorByFuncName":            reflect.ValueOf(insyra.PopErrorByFuncName),
		"PopErrorByPackageName":         reflect.ValueOf(insyra.PopErrorByPackageName),
		"PopErrorInfo":                  reflect.ValueOf(insyra.PopErrorInfo),
		"PowRat":                        reflect.ValueOf(insyra.PowRat),
		"ProcessData":                   reflect.ValueOf(insyra.ProcessData),
		"ReadCSV_File":                  reflect.ValueOf(insyra.ReadCSV_File),
		"ReadCSV_String":                reflect.ValueOf(insyra.ReadCSV_String),
		"ReadExcelSheet":                reflect.ValueOf(insyra.ReadExcelSheet),
		"ReadJSON":                      reflect.ValueOf(insyra.ReadJSON),
		"ReadJSON_File":                 reflect.ValueOf(insyra.ReadJSON_File),
		"ReadSQL":                       reflect.ValueOf(insyra.ReadSQL),
		"ReadSlice2D":                   reflect.ValueOf(&insyra.ReadSlice2D).Elem(),
		"SQLActionIfTableExistsAppend":  reflect.ValueOf(insyra.SQLActionIfTableExistsAppend),
		"SQLActionIfTableExistsFail":    reflect.ValueOf(insyra.SQLActionIfTableExistsFail),
		"SQLActionIfTableExistsReplace": reflect.ValueOf(insyra.SQLActionIfTableExistsReplace),
		"SetDefaultConfig":              reflect.ValueOf(insyra.SetDefaultConfig),
		"Show":                          reflect.ValueOf(insyra.Show),
		"Slice2DToDataTable":            reflect.ValueOf(insyra.Slice2DToDataTable),
		"SliceToF64":                    reflect.ValueOf(insyra.SliceToF64),
		"SortTimes":                     reflect.ValueOf(insyra.SortTimes),
		"SqrtRat":                       reflect.ValueOf(insyra.SqrtRat),
		"ToFloat64":                     reflect.ValueOf(&insyra.ToFloat64).Elem(),
		"ToFloat64Safe":                 reflect.ValueOf(&insyra.ToFloat64Safe).Elem(),
		"Version":                       reflect.ValueOf(constant.MakeFromLiteral("\"0.2.13\"", token.STRING, 0)),
		"VersionName":                   reflect.ValueOf(constant.MakeFromLiteral("\"Pier-2\"", token.STRING, 0)),

		// type definitions
		"DataList":               reflect.ValueOf((*insyra.DataList)(nil)),
		"DataTable":              reflect.ValueOf((*insyra.DataTable)(nil)),
		"DataTableSortConfig":    reflect.ValueOf((*insyra.DataTableSortConfig)(nil)),
		"ErrPoppingMode":         reflect.ValueOf((*insyra.ErrPoppingMode)(nil)),
		"ErrorInfo":              reflect.ValueOf((*insyra.ErrorInfo)(nil)),
		"IDataList":              reflect.ValueOf((*insyra.IDataList)(nil)),
		"IDataTable":             reflect.ValueOf((*insyra.IDataTable)(nil)),
		"LogLevel":               reflect.ValueOf((*insyra.LogLevel)(nil)),
		"MergeDirection":         reflect.ValueOf((*insyra.MergeDirection)(nil)),
		"MergeMode":              reflect.ValueOf((*insyra.MergeMode)(nil)),
		"ReadSQLOptions":         reflect.ValueOf((*insyra.ReadSQLOptions)(nil)),
		"SQLActionIfTableExists": reflect.ValueOf((*insyra.SQLActionIfTableExists)(nil)),
		"ToSQLOptions":           reflect.ValueOf((*insyra.ToSQLOptions)(nil)),

		// interface wrapper definitions
		"_IDataList":  reflect.ValueOf((*_github_com_HazelnutParadise_insyra_IDataList)(nil)),
		"_IDataTable": reflect.ValueOf((*_github_com_HazelnutParadise_insyra_IDataTable)(nil)),
	}
}

// _github_com_HazelnutParadise_insyra_IDataList is an interface wrapper for IDataList type
type _github_com_HazelnutParadise_insyra_IDataList struct {
	IValue                        interface{}
	WAppend                       func(values ...any) *insyra.DataList
	WAppendDataList               func(other insyra.IDataList) *insyra.DataList
	WAtomicDo                     func(a0 func(*insyra.DataList))
	WCapitalize                   func() *insyra.DataList
	WClear                        func() *insyra.DataList
	WClearErr                     func() *insyra.DataList
	WClearNaNs                    func() *insyra.DataList
	WClearNils                    func() *insyra.DataList
	WClearNilsAndNaNs             func() *insyra.DataList
	WClearNumbers                 func() *insyra.DataList
	WClearOutliers                func(a0 float64) *insyra.DataList
	WClearStrings                 func() *insyra.DataList
	WClone                        func() *insyra.DataList
	WConcat                       func(other insyra.IDataList) *insyra.DataList
	WCount                        func(value any) int
	WCounter                      func() map[any]int
	WData                         func() []any
	WDifference                   func() *insyra.DataList
	WDoubleExponentialSmoothing   func(a0 float64, a1 float64) *insyra.DataList
	WDrop                         func(index int) *insyra.DataList
	WDropAll                      func(a0 ...any) *insyra.DataList
	WDropIfContains               func(a0 string) *insyra.DataList
	WErr                          func() *insyra.ErrorInfo
	WExponentialSmoothing         func(a0 float64) *insyra.DataList
	WFillNaNWithMean              func() *insyra.DataList
	WFilter                       func(a0 func(any) bool) *insyra.DataList
	WFindAll                      func(a0 any) []int
	WFindFirst                    func(a0 any) any
	WFindLast                     func(a0 any) any
	WGMean                        func() float64
	WGet                          func(index int) any
	WGetCreationTimestamp         func() int64
	WGetLastModifiedTimestamp     func() int64
	WGetName                      func() string
	WHermiteInterpolation         func(a0 float64, a1 []float64) float64
	WIQR                          func() float64
	WInsertAt                     func(index int, value any) *insyra.DataList
	WIsEqualTo                    func(a0 *insyra.DataList) bool
	WIsTheSameAs                  func(a0 *insyra.DataList) bool
	WLagrangeInterpolation        func(a0 float64) float64
	WLen                          func() int
	WLinearInterpolation          func(a0 float64) float64
	WLower                        func() *insyra.DataList
	WMAD                          func() float64
	WMap                          func(mapFunc func(int, any) any) *insyra.DataList
	WMax                          func() float64
	WMean                         func() float64
	WMedian                       func() float64
	WMin                          func() float64
	WMode                         func() []float64
	WMovingAverage                func(a0 int) *insyra.DataList
	WMovingStdev                  func(a0 int) *insyra.DataList
	WNearestNeighborInterpolation func(a0 float64) float64
	WNewtonInterpolation          func(a0 float64) float64
	WNormalize                    func() *insyra.DataList
	WParseNumbers                 func() *insyra.DataList
	WParseStrings                 func() *insyra.DataList
	WPercentile                   func(a0 float64) float64
	WPop                          func() any
	WQuadraticInterpolation       func(a0 float64) float64
	WQuartile                     func(a0 int) float64
	WRange                        func() float64
	WRank                         func() *insyra.DataList
	WReplaceAll                   func(a0 any, a1 any) *insyra.DataList
	WReplaceFirst                 func(a0 any, a1 any) *insyra.DataList
	WReplaceLast                  func(a0 any, a1 any) *insyra.DataList
	WReplaceNaNsAndNilsWith       func(a0 any) *insyra.DataList
	WReplaceNaNsWith              func(a0 any) *insyra.DataList
	WReplaceNilsWith              func(a0 any) *insyra.DataList
	WReplaceOutliers              func(a0 float64, a1 float64) *insyra.DataList
	WReverse                      func() *insyra.DataList
	WSetName                      func(a0 string) *insyra.DataList
	WShow                         func()
	WShowRange                    func(startEnd ...any)
	WShowTypes                    func()
	WShowTypesRange               func(startEnd ...any)
	WSort                         func(ascending ...bool) *insyra.DataList
	WStandardize                  func() *insyra.DataList
	WStdev                        func() float64
	WStdevP                       func() float64
	WSum                          func() float64
	WSummary                      func()
	WToF64Slice                   func() []float64
	WToStringSlice                func() []string
	WUpdate                       func(index int, value any) *insyra.DataList
	WUpper                        func() *insyra.DataList
	WVar                          func() float64
	WVarP                         func() float64
	WWeightedMean                 func(weights any) float64
	WWeightedMovingAverage        func(a0 int, a1 any) *insyra.DataList
}

func (W _github_com_HazelnutParadise_insyra_IDataList) Append(values ...any) *insyra.DataList {
	return W.WAppend(values...)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) AppendDataList(other insyra.IDataList) *insyra.DataList {
	return W.WAppendDataList(other)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) AtomicDo(a0 func(*insyra.DataList)) {
	W.WAtomicDo(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Capitalize() *insyra.DataList {
	return W.WCapitalize()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Clear() *insyra.DataList {
	return W.WClear()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ClearErr() *insyra.DataList {
	return W.WClearErr()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ClearNaNs() *insyra.DataList {
	return W.WClearNaNs()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ClearNils() *insyra.DataList {
	return W.WClearNils()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ClearNilsAndNaNs() *insyra.DataList {
	return W.WClearNilsAndNaNs()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ClearNumbers() *insyra.DataList {
	return W.WClearNumbers()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ClearOutliers(a0 float64) *insyra.DataList {
	return W.WClearOutliers(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ClearStrings() *insyra.DataList {
	return W.WClearStrings()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Clone() *insyra.DataList {
	return W.WClone()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Concat(other insyra.IDataList) *insyra.DataList {
	return W.WConcat(other)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Count(value any) int {
	return W.WCount(value)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Counter() map[any]int {
	return W.WCounter()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Data() []any {
	return W.WData()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Difference() *insyra.DataList {
	return W.WDifference()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) DoubleExponentialSmoothing(a0 float64, a1 float64) *insyra.DataList {
	return W.WDoubleExponentialSmoothing(a0, a1)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Drop(index int) *insyra.DataList {
	return W.WDrop(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) DropAll(a0 ...any) *insyra.DataList {
	return W.WDropAll(a0...)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) DropIfContains(a0 string) *insyra.DataList {
	return W.WDropIfContains(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Err() *insyra.ErrorInfo {
	return W.WErr()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ExponentialSmoothing(a0 float64) *insyra.DataList {
	return W.WExponentialSmoothing(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) FillNaNWithMean() *insyra.DataList {
	return W.WFillNaNWithMean()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Filter(a0 func(any) bool) *insyra.DataList {
	return W.WFilter(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) FindAll(a0 any) []int {
	return W.WFindAll(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) FindFirst(a0 any) any {
	return W.WFindFirst(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) FindLast(a0 any) any {
	return W.WFindLast(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) GMean() float64 {
	return W.WGMean()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Get(index int) any {
	return W.WGet(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) GetCreationTimestamp() int64 {
	return W.WGetCreationTimestamp()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) GetLastModifiedTimestamp() int64 {
	return W.WGetLastModifiedTimestamp()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) GetName() string {
	return W.WGetName()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) HermiteInterpolation(a0 float64, a1 []float64) float64 {
	return W.WHermiteInterpolation(a0, a1)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) IQR() float64 {
	return W.WIQR()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) InsertAt(index int, value any) *insyra.DataList {
	return W.WInsertAt(index, value)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) IsEqualTo(a0 *insyra.DataList) bool {
	return W.WIsEqualTo(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) IsTheSameAs(a0 *insyra.DataList) bool {
	return W.WIsTheSameAs(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) LagrangeInterpolation(a0 float64) float64 {
	return W.WLagrangeInterpolation(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Len() int {
	return W.WLen()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) LinearInterpolation(a0 float64) float64 {
	return W.WLinearInterpolation(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Lower() *insyra.DataList {
	return W.WLower()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) MAD() float64 {
	return W.WMAD()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Map(mapFunc func(int, any) any) *insyra.DataList {
	return W.WMap(mapFunc)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Max() float64 {
	return W.WMax()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Mean() float64 {
	return W.WMean()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Median() float64 {
	return W.WMedian()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Min() float64 {
	return W.WMin()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Mode() []float64 {
	return W.WMode()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) MovingAverage(a0 int) *insyra.DataList {
	return W.WMovingAverage(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) MovingStdev(a0 int) *insyra.DataList {
	return W.WMovingStdev(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) NearestNeighborInterpolation(a0 float64) float64 {
	return W.WNearestNeighborInterpolation(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) NewtonInterpolation(a0 float64) float64 {
	return W.WNewtonInterpolation(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Normalize() *insyra.DataList {
	return W.WNormalize()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ParseNumbers() *insyra.DataList {
	return W.WParseNumbers()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ParseStrings() *insyra.DataList {
	return W.WParseStrings()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Percentile(a0 float64) float64 {
	return W.WPercentile(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Pop() any {
	return W.WPop()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) QuadraticInterpolation(a0 float64) float64 {
	return W.WQuadraticInterpolation(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Quartile(a0 int) float64 {
	return W.WQuartile(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Range() float64 {
	return W.WRange()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Rank() *insyra.DataList {
	return W.WRank()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ReplaceAll(a0 any, a1 any) *insyra.DataList {
	return W.WReplaceAll(a0, a1)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ReplaceFirst(a0 any, a1 any) *insyra.DataList {
	return W.WReplaceFirst(a0, a1)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ReplaceLast(a0 any, a1 any) *insyra.DataList {
	return W.WReplaceLast(a0, a1)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ReplaceNaNsAndNilsWith(a0 any) *insyra.DataList {
	return W.WReplaceNaNsAndNilsWith(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ReplaceNaNsWith(a0 any) *insyra.DataList {
	return W.WReplaceNaNsWith(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ReplaceNilsWith(a0 any) *insyra.DataList {
	return W.WReplaceNilsWith(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ReplaceOutliers(a0 float64, a1 float64) *insyra.DataList {
	return W.WReplaceOutliers(a0, a1)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Reverse() *insyra.DataList {
	return W.WReverse()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) SetName(a0 string) *insyra.DataList {
	return W.WSetName(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Show() {
	W.WShow()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ShowRange(startEnd ...any) {
	W.WShowRange(startEnd...)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ShowTypes() {
	W.WShowTypes()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ShowTypesRange(startEnd ...any) {
	W.WShowTypesRange(startEnd...)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Sort(ascending ...bool) *insyra.DataList {
	return W.WSort(ascending...)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Standardize() *insyra.DataList {
	return W.WStandardize()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Stdev() float64 {
	return W.WStdev()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) StdevP() float64 {
	return W.WStdevP()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Sum() float64 {
	return W.WSum()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Summary() {
	W.WSummary()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ToF64Slice() []float64 {
	return W.WToF64Slice()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) ToStringSlice() []string {
	return W.WToStringSlice()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Update(index int, value any) *insyra.DataList {
	return W.WUpdate(index, value)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Upper() *insyra.DataList {
	return W.WUpper()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) Var() float64 {
	return W.WVar()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) VarP() float64 {
	return W.WVarP()
}
func (W _github_com_HazelnutParadise_insyra_IDataList) WeightedMean(weights any) float64 {
	return W.WWeightedMean(weights)
}
func (W _github_com_HazelnutParadise_insyra_IDataList) WeightedMovingAverage(a0 int, a1 any) *insyra.DataList {
	return W.WWeightedMovingAverage(a0, a1)
}

// _github_com_HazelnutParadise_insyra_IDataTable is an interface wrapper for IDataTable type
type _github_com_HazelnutParadise_insyra_IDataTable struct {
	IValue                                    interface{}
	WAddColUsingCCL                           func(newColName string, ccl string) *insyra.DataTable
	WAppendCols                               func(columns ...*insyra.DataList) *insyra.DataTable
	WAppendRowsByColIndex                     func(rowsData ...map[string]any) *insyra.DataTable
	WAppendRowsByColName                      func(rowsData ...map[string]any) *insyra.DataTable
	WAppendRowsFromDataList                   func(rowsData ...*insyra.DataList) *insyra.DataTable
	WAtomicDo                                 func(a0 func(*insyra.DataTable))
	WChangeColName                            func(oldName string, newName string) *insyra.DataTable
	WChangeRowName                            func(oldName string, newName string) *insyra.DataTable
	WClearErr                                 func() *insyra.DataTable
	WClone                                    func() *insyra.DataTable
	WColNames                                 func() []string
	WColNamesToFirstRow                       func() *insyra.DataTable
	WCount                                    func(value any) int
	WData                                     func(useNamesAsKeys ...bool) map[string][]any
	WDropColNames                             func() *insyra.DataTable
	WDropColsByIndex                          func(columnIndices ...string) *insyra.DataTable
	WDropColsByName                           func(columnNames ...string) *insyra.DataTable
	WDropColsByNumber                         func(columnIndices ...int) *insyra.DataTable
	WDropColsContain                          func(value ...any) *insyra.DataTable
	WDropColsContainExcelNA                   func() *insyra.DataTable
	WDropColsContainNaN                       func() *insyra.DataTable
	WDropColsContainNil                       func() *insyra.DataTable
	WDropColsContainNumber                    func() *insyra.DataTable
	WDropColsContainString                    func() *insyra.DataTable
	WDropRowNames                             func() *insyra.DataTable
	WDropRowsByIndex                          func(rowIndices ...int) *insyra.DataTable
	WDropRowsByName                           func(rowNames ...string) *insyra.DataTable
	WDropRowsContain                          func(value ...any) *insyra.DataTable
	WDropRowsContainExcelNA                   func() *insyra.DataTable
	WDropRowsContainNaN                       func() *insyra.DataTable
	WDropRowsContainNil                       func() *insyra.DataTable
	WDropRowsContainNumber                    func() *insyra.DataTable
	WDropRowsContainString                    func() *insyra.DataTable
	WErr                                      func() *insyra.ErrorInfo
	WFilter                                   func(filterFunc func(rowIndex int, columnIndex string, value any) bool) *insyra.DataTable
	WFilterByCustomElement                    func(f func(value any) bool) *insyra.DataTable
	WFilterCols                               func(filterFunc func(rowIndex int, rowName string, x any) bool) *insyra.DataTable
	WFilterColsByColIndexEqualTo              func(index string) *insyra.DataTable
	WFilterColsByColIndexGreaterThan          func(threshold string) *insyra.DataTable
	WFilterColsByColIndexGreaterThanOrEqualTo func(threshold string) *insyra.DataTable
	WFilterColsByColIndexLessThan             func(threshold string) *insyra.DataTable
	WFilterColsByColIndexLessThanOrEqualTo    func(threshold string) *insyra.DataTable
	WFilterColsByColNameContains              func(substring string) *insyra.DataTable
	WFilterColsByColNameEqualTo               func(name string) *insyra.DataTable
	WFilterRows                               func(filterFunc func(colIndex string, colName string, x any) bool) *insyra.DataTable
	WFilterRowsByRowIndexEqualTo              func(index int) *insyra.DataTable
	WFilterRowsByRowIndexGreaterThan          func(threshold int) *insyra.DataTable
	WFilterRowsByRowIndexGreaterThanOrEqualTo func(threshold int) *insyra.DataTable
	WFilterRowsByRowIndexLessThan             func(threshold int) *insyra.DataTable
	WFilterRowsByRowIndexLessThanOrEqualTo    func(threshold int) *insyra.DataTable
	WFilterRowsByRowNameContains              func(substring string) *insyra.DataTable
	WFilterRowsByRowNameEqualTo               func(name string) *insyra.DataTable
	WFindColsIfAllElementsContainSubstring    func(substring string) []string
	WFindColsIfAnyElementContainsSubstring    func(substring string) []string
	WFindColsIfContains                       func(value any) []string
	WFindColsIfContainsAll                    func(values ...any) []string
	WFindRowsIfAllElementsContainSubstring    func(substring string) []int
	WFindRowsIfAnyElementContainsSubstring    func(substring string) []int
	WFindRowsIfContains                       func(value any) []int
	WFindRowsIfContainsAll                    func(values ...any) []int
	WGetCol                                   func(index string) *insyra.DataList
	WGetColByName                             func(name string) *insyra.DataList
	WGetColByNumber                           func(index int) *insyra.DataList
	WGetColIndexByName                        func(name string) string
	WGetColIndexByNumber                      func(number int) string
	WGetColNameByNumber                       func(index int) string
	WGetColNumberByName                       func(name string) int
	WGetCreationTimestamp                     func() int64
	WGetElement                               func(rowIndex int, columnIndex string) any
	WGetElementByNumberIndex                  func(rowIndex int, columnIndex int) any
	WGetLastModifiedTimestamp                 func() int64
	WGetName                                  func() string
	WGetRow                                   func(index int) *insyra.DataList
	WGetRowByName                             func(name string) *insyra.DataList
	WGetRowIndexByName                        func(name string) (int, bool)
	WGetRowNameByIndex                        func(index int) (string, bool)
	WHeaders                                  func() []string
	WMap                                      func(mapFunc func(rowIndex int, colIndex string, element any) any) *insyra.DataTable
	WMean                                     func() any
	WMerge                                    func(other insyra.IDataTable, direction insyra.MergeDirection, mode insyra.MergeMode, on ...string) (*insyra.DataTable, error)
	WNumCols                                  func() int
	WNumRows                                  func() int
	WReplace                                  func(oldValue any, newValue any) *insyra.DataTable
	WReplaceInCol                             func(colIndex string, oldValue any, newValue any, mode ...int) *insyra.DataTable
	WReplaceInRow                             func(rowIndex int, oldValue any, newValue any, mode ...int) *insyra.DataTable
	WReplaceNaNsAndNilsInCol                  func(colIndex string, newValue any, mode ...int) *insyra.DataTable
	WReplaceNaNsAndNilsInRow                  func(rowIndex int, newValue any, mode ...int) *insyra.DataTable
	WReplaceNaNsAndNilsWith                   func(newValue any) *insyra.DataTable
	WReplaceNaNsInCol                         func(colIndex string, newValue any, mode ...int) *insyra.DataTable
	WReplaceNaNsInRow                         func(rowIndex int, newValue any, mode ...int) *insyra.DataTable
	WReplaceNaNsWith                          func(newValue any) *insyra.DataTable
	WReplaceNilsInCol                         func(colIndex string, newValue any, mode ...int) *insyra.DataTable
	WReplaceNilsInRow                         func(rowIndex int, newValue any, mode ...int) *insyra.DataTable
	WReplaceNilsWith                          func(newValue any) *insyra.DataTable
	WRowNames                                 func() []string
	WRowNamesToFirstCol                       func() *insyra.DataTable
	WSetColNameByIndex                        func(index string, name string) *insyra.DataTable
	WSetColNameByNumber                       func(numberIndex int, name string) *insyra.DataTable
	WSetColNames                              func(colNames []string) *insyra.DataTable
	WSetColToRowNames                         func(columnIndex string) *insyra.DataTable
	WSetHeaders                               func(headers []string) *insyra.DataTable
	WSetName                                  func(name string) *insyra.DataTable
	WSetRowNameByIndex                        func(index int, name string) *insyra.DataTable
	WSetRowNames                              func(rowNames []string) *insyra.DataTable
	WSetRowToColNames                         func(rowIndex int) *insyra.DataTable
	WShow                                     func()
	WShowRange                                func(startEnd ...any)
	WShowTypes                                func()
	WShowTypesRange                           func(startEnd ...any)
	WSimpleRandomSample                       func(sampleSize int) *insyra.DataTable
	WSize                                     func() (numRows int, numCols int)
	WSortBy                                   func(configs ...insyra.DataTableSortConfig) *insyra.DataTable
	WSummary                                  func()
	WSwapColsByIndex                          func(columnIndex1 string, columnIndex2 string) *insyra.DataTable
	WSwapColsByName                           func(columnName1 string, columnName2 string) *insyra.DataTable
	WSwapColsByNumber                         func(columnNumber1 int, columnNumber2 int) *insyra.DataTable
	WSwapRowsByIndex                          func(rowIndex1 int, rowIndex2 int) *insyra.DataTable
	WSwapRowsByName                           func(rowName1 string, rowName2 string) *insyra.DataTable
	WTo2DSlice                                func() [][]any
	WToCSV                                    func(filePath string, setRowNamesToFirstCol bool, setColNamesToFirstRow bool, includeBOM bool) error
	WToJSON                                   func(filePath string, useColNames bool) error
	WToJSON_Bytes                             func(useColNames bool) []byte
	WToJSON_String                            func(useColNames bool) string
	WToMap                                    func(useNamesAsKeys ...bool) map[string][]any
	WToSQL                                    func(db *gorm.DB, tableName string, options ...insyra.ToSQLOptions) error
	WTranspose                                func() *insyra.DataTable
	WUpdateCol                                func(index string, dl *insyra.DataList) *insyra.DataTable
	WUpdateColByNumber                        func(index int, dl *insyra.DataList) *insyra.DataTable
	WUpdateElement                            func(rowIndex int, columnIndex string, value any) *insyra.DataTable
	WUpdateRow                                func(index int, dl *insyra.DataList) *insyra.DataTable
}

func (W _github_com_HazelnutParadise_insyra_IDataTable) AddColUsingCCL(newColName string, ccl string) *insyra.DataTable {
	return W.WAddColUsingCCL(newColName, ccl)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) AppendCols(columns ...*insyra.DataList) *insyra.DataTable {
	return W.WAppendCols(columns...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) AppendRowsByColIndex(rowsData ...map[string]any) *insyra.DataTable {
	return W.WAppendRowsByColIndex(rowsData...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) AppendRowsByColName(rowsData ...map[string]any) *insyra.DataTable {
	return W.WAppendRowsByColName(rowsData...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) AppendRowsFromDataList(rowsData ...*insyra.DataList) *insyra.DataTable {
	return W.WAppendRowsFromDataList(rowsData...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) AtomicDo(a0 func(*insyra.DataTable)) {
	W.WAtomicDo(a0)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ChangeColName(oldName string, newName string) *insyra.DataTable {
	return W.WChangeColName(oldName, newName)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ChangeRowName(oldName string, newName string) *insyra.DataTable {
	return W.WChangeRowName(oldName, newName)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ClearErr() *insyra.DataTable {
	return W.WClearErr()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Clone() *insyra.DataTable {
	return W.WClone()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ColNames() []string {
	return W.WColNames()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ColNamesToFirstRow() *insyra.DataTable {
	return W.WColNamesToFirstRow()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Count(value any) int {
	return W.WCount(value)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Data(useNamesAsKeys ...bool) map[string][]any {
	return W.WData(useNamesAsKeys...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColNames() *insyra.DataTable {
	return W.WDropColNames()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsByIndex(columnIndices ...string) *insyra.DataTable {
	return W.WDropColsByIndex(columnIndices...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsByName(columnNames ...string) *insyra.DataTable {
	return W.WDropColsByName(columnNames...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsByNumber(columnIndices ...int) *insyra.DataTable {
	return W.WDropColsByNumber(columnIndices...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsContain(value ...any) *insyra.DataTable {
	return W.WDropColsContain(value...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsContainExcelNA() *insyra.DataTable {
	return W.WDropColsContainExcelNA()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsContainNaN() *insyra.DataTable {
	return W.WDropColsContainNaN()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsContainNil() *insyra.DataTable {
	return W.WDropColsContainNil()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsContainNumber() *insyra.DataTable {
	return W.WDropColsContainNumber()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropColsContainString() *insyra.DataTable {
	return W.WDropColsContainString()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowNames() *insyra.DataTable {
	return W.WDropRowNames()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsByIndex(rowIndices ...int) *insyra.DataTable {
	return W.WDropRowsByIndex(rowIndices...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsByName(rowNames ...string) *insyra.DataTable {
	return W.WDropRowsByName(rowNames...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsContain(value ...any) *insyra.DataTable {
	return W.WDropRowsContain(value...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsContainExcelNA() *insyra.DataTable {
	return W.WDropRowsContainExcelNA()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsContainNaN() *insyra.DataTable {
	return W.WDropRowsContainNaN()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsContainNil() *insyra.DataTable {
	return W.WDropRowsContainNil()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsContainNumber() *insyra.DataTable {
	return W.WDropRowsContainNumber()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) DropRowsContainString() *insyra.DataTable {
	return W.WDropRowsContainString()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Err() *insyra.ErrorInfo {
	return W.WErr()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Filter(filterFunc func(rowIndex int, columnIndex string, value any) bool) *insyra.DataTable {
	return W.WFilter(filterFunc)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterByCustomElement(f func(value any) bool) *insyra.DataTable {
	return W.WFilterByCustomElement(f)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterCols(filterFunc func(rowIndex int, rowName string, x any) bool) *insyra.DataTable {
	return W.WFilterCols(filterFunc)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterColsByColIndexEqualTo(index string) *insyra.DataTable {
	return W.WFilterColsByColIndexEqualTo(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterColsByColIndexGreaterThan(threshold string) *insyra.DataTable {
	return W.WFilterColsByColIndexGreaterThan(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterColsByColIndexGreaterThanOrEqualTo(threshold string) *insyra.DataTable {
	return W.WFilterColsByColIndexGreaterThanOrEqualTo(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterColsByColIndexLessThan(threshold string) *insyra.DataTable {
	return W.WFilterColsByColIndexLessThan(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterColsByColIndexLessThanOrEqualTo(threshold string) *insyra.DataTable {
	return W.WFilterColsByColIndexLessThanOrEqualTo(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterColsByColNameContains(substring string) *insyra.DataTable {
	return W.WFilterColsByColNameContains(substring)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterColsByColNameEqualTo(name string) *insyra.DataTable {
	return W.WFilterColsByColNameEqualTo(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRows(filterFunc func(colIndex string, colName string, x any) bool) *insyra.DataTable {
	return W.WFilterRows(filterFunc)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRowsByRowIndexEqualTo(index int) *insyra.DataTable {
	return W.WFilterRowsByRowIndexEqualTo(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRowsByRowIndexGreaterThan(threshold int) *insyra.DataTable {
	return W.WFilterRowsByRowIndexGreaterThan(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRowsByRowIndexGreaterThanOrEqualTo(threshold int) *insyra.DataTable {
	return W.WFilterRowsByRowIndexGreaterThanOrEqualTo(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRowsByRowIndexLessThan(threshold int) *insyra.DataTable {
	return W.WFilterRowsByRowIndexLessThan(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRowsByRowIndexLessThanOrEqualTo(threshold int) *insyra.DataTable {
	return W.WFilterRowsByRowIndexLessThanOrEqualTo(threshold)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRowsByRowNameContains(substring string) *insyra.DataTable {
	return W.WFilterRowsByRowNameContains(substring)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FilterRowsByRowNameEqualTo(name string) *insyra.DataTable {
	return W.WFilterRowsByRowNameEqualTo(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindColsIfAllElementsContainSubstring(substring string) []string {
	return W.WFindColsIfAllElementsContainSubstring(substring)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindColsIfAnyElementContainsSubstring(substring string) []string {
	return W.WFindColsIfAnyElementContainsSubstring(substring)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindColsIfContains(value any) []string {
	return W.WFindColsIfContains(value)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindColsIfContainsAll(values ...any) []string {
	return W.WFindColsIfContainsAll(values...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindRowsIfAllElementsContainSubstring(substring string) []int {
	return W.WFindRowsIfAllElementsContainSubstring(substring)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindRowsIfAnyElementContainsSubstring(substring string) []int {
	return W.WFindRowsIfAnyElementContainsSubstring(substring)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindRowsIfContains(value any) []int {
	return W.WFindRowsIfContains(value)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) FindRowsIfContainsAll(values ...any) []int {
	return W.WFindRowsIfContainsAll(values...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetCol(index string) *insyra.DataList {
	return W.WGetCol(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetColByName(name string) *insyra.DataList {
	return W.WGetColByName(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetColByNumber(index int) *insyra.DataList {
	return W.WGetColByNumber(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetColIndexByName(name string) string {
	return W.WGetColIndexByName(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetColIndexByNumber(number int) string {
	return W.WGetColIndexByNumber(number)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetColNameByNumber(index int) string {
	return W.WGetColNameByNumber(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetColNumberByName(name string) int {
	return W.WGetColNumberByName(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetCreationTimestamp() int64 {
	return W.WGetCreationTimestamp()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetElement(rowIndex int, columnIndex string) any {
	return W.WGetElement(rowIndex, columnIndex)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetElementByNumberIndex(rowIndex int, columnIndex int) any {
	return W.WGetElementByNumberIndex(rowIndex, columnIndex)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetLastModifiedTimestamp() int64 {
	return W.WGetLastModifiedTimestamp()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetName() string {
	return W.WGetName()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetRow(index int) *insyra.DataList {
	return W.WGetRow(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetRowByName(name string) *insyra.DataList {
	return W.WGetRowByName(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetRowIndexByName(name string) (int, bool) {
	return W.WGetRowIndexByName(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) GetRowNameByIndex(index int) (string, bool) {
	return W.WGetRowNameByIndex(index)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Headers() []string {
	return W.WHeaders()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Map(mapFunc func(rowIndex int, colIndex string, element any) any) *insyra.DataTable {
	return W.WMap(mapFunc)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Mean() any {
	return W.WMean()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Merge(other insyra.IDataTable, direction insyra.MergeDirection, mode insyra.MergeMode, on ...string) (*insyra.DataTable, error) {
	return W.WMerge(other, direction, mode, on...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) NumCols() int {
	return W.WNumCols()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) NumRows() int {
	return W.WNumRows()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Replace(oldValue any, newValue any) *insyra.DataTable {
	return W.WReplace(oldValue, newValue)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceInCol(colIndex string, oldValue any, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceInCol(colIndex, oldValue, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceInRow(rowIndex int, oldValue any, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceInRow(rowIndex, oldValue, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNaNsAndNilsInCol(colIndex string, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceNaNsAndNilsInCol(colIndex, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNaNsAndNilsInRow(rowIndex int, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceNaNsAndNilsInRow(rowIndex, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNaNsAndNilsWith(newValue any) *insyra.DataTable {
	return W.WReplaceNaNsAndNilsWith(newValue)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNaNsInCol(colIndex string, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceNaNsInCol(colIndex, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNaNsInRow(rowIndex int, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceNaNsInRow(rowIndex, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNaNsWith(newValue any) *insyra.DataTable {
	return W.WReplaceNaNsWith(newValue)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNilsInCol(colIndex string, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceNilsInCol(colIndex, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNilsInRow(rowIndex int, newValue any, mode ...int) *insyra.DataTable {
	return W.WReplaceNilsInRow(rowIndex, newValue, mode...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ReplaceNilsWith(newValue any) *insyra.DataTable {
	return W.WReplaceNilsWith(newValue)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) RowNames() []string {
	return W.WRowNames()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) RowNamesToFirstCol() *insyra.DataTable {
	return W.WRowNamesToFirstCol()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetColNameByIndex(index string, name string) *insyra.DataTable {
	return W.WSetColNameByIndex(index, name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetColNameByNumber(numberIndex int, name string) *insyra.DataTable {
	return W.WSetColNameByNumber(numberIndex, name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetColNames(colNames []string) *insyra.DataTable {
	return W.WSetColNames(colNames)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetColToRowNames(columnIndex string) *insyra.DataTable {
	return W.WSetColToRowNames(columnIndex)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetHeaders(headers []string) *insyra.DataTable {
	return W.WSetHeaders(headers)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetName(name string) *insyra.DataTable {
	return W.WSetName(name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetRowNameByIndex(index int, name string) *insyra.DataTable {
	return W.WSetRowNameByIndex(index, name)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetRowNames(rowNames []string) *insyra.DataTable {
	return W.WSetRowNames(rowNames)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SetRowToColNames(rowIndex int) *insyra.DataTable {
	return W.WSetRowToColNames(rowIndex)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Show() {
	W.WShow()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ShowRange(startEnd ...any) {
	W.WShowRange(startEnd...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ShowTypes() {
	W.WShowTypes()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ShowTypesRange(startEnd ...any) {
	W.WShowTypesRange(startEnd...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SimpleRandomSample(sampleSize int) *insyra.DataTable {
	return W.WSimpleRandomSample(sampleSize)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Size() (numRows int, numCols int) {
	return W.WSize()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SortBy(configs ...insyra.DataTableSortConfig) *insyra.DataTable {
	return W.WSortBy(configs...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Summary() {
	W.WSummary()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SwapColsByIndex(columnIndex1 string, columnIndex2 string) *insyra.DataTable {
	return W.WSwapColsByIndex(columnIndex1, columnIndex2)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SwapColsByName(columnName1 string, columnName2 string) *insyra.DataTable {
	return W.WSwapColsByName(columnName1, columnName2)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SwapColsByNumber(columnNumber1 int, columnNumber2 int) *insyra.DataTable {
	return W.WSwapColsByNumber(columnNumber1, columnNumber2)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SwapRowsByIndex(rowIndex1 int, rowIndex2 int) *insyra.DataTable {
	return W.WSwapRowsByIndex(rowIndex1, rowIndex2)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) SwapRowsByName(rowName1 string, rowName2 string) *insyra.DataTable {
	return W.WSwapRowsByName(rowName1, rowName2)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) To2DSlice() [][]any {
	return W.WTo2DSlice()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ToCSV(filePath string, setRowNamesToFirstCol bool, setColNamesToFirstRow bool, includeBOM bool) error {
	return W.WToCSV(filePath, setRowNamesToFirstCol, setColNamesToFirstRow, includeBOM)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ToJSON(filePath string, useColNames bool) error {
	return W.WToJSON(filePath, useColNames)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ToJSON_Bytes(useColNames bool) []byte {
	return W.WToJSON_Bytes(useColNames)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ToJSON_String(useColNames bool) string {
	return W.WToJSON_String(useColNames)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ToMap(useNamesAsKeys ...bool) map[string][]any {
	return W.WToMap(useNamesAsKeys...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) ToSQL(db *gorm.DB, tableName string, options ...insyra.ToSQLOptions) error {
	return W.WToSQL(db, tableName, options...)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) Transpose() *insyra.DataTable {
	return W.WTranspose()
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) UpdateCol(index string, dl *insyra.DataList) *insyra.DataTable {
	return W.WUpdateCol(index, dl)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) UpdateColByNumber(index int, dl *insyra.DataList) *insyra.DataTable {
	return W.WUpdateColByNumber(index, dl)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) UpdateElement(rowIndex int, columnIndex string, value any) *insyra.DataTable {
	return W.WUpdateElement(rowIndex, columnIndex, value)
}
func (W _github_com_HazelnutParadise_insyra_IDataTable) UpdateRow(index int, dl *insyra.DataList) *insyra.DataTable {
	return W.WUpdateRow(index, dl)
}
