// Code generated by 'yaegi extract github.com/HazelnutParadise/insyra/plot'. DO NOT EDIT.

package internal

import (
	"github.com/HazelnutParadise/insyra/plot"
	"io"
	"reflect"
)

func init() {
	Symbols["github.com/HazelnutParadise/insyra/plot/plot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CreateBarChart":                 reflect.ValueOf(plot.CreateBarChart),
		"CreateBoxPlot":                  reflect.ValueOf(plot.CreateBoxPlot),
		"CreateFunnelChart":              reflect.ValueOf(plot.CreateFunnelChart),
		"CreateGaugeChart":               reflect.ValueOf(plot.CreateGaugeChart),
		"CreateKlineChart":               reflect.ValueOf(plot.CreateKlineChart),
		"CreateLineChart":                reflect.ValueOf(plot.CreateLineChart),
		"CreatePieChart":                 reflect.ValueOf(plot.CreatePieChart),
		"CreateRadarChart":               reflect.ValueOf(plot.CreateRadarChart),
		"CreateSankeyChart":              reflect.ValueOf(plot.CreateSankeyChart),
		"CreateScatterChart":             reflect.ValueOf(plot.CreateScatterChart),
		"CreateThemeRiverChart":          reflect.ValueOf(plot.CreateThemeRiverChart),
		"CreateWordCloud":                reflect.ValueOf(plot.CreateWordCloud),
		"LabelPositionBottom":            reflect.ValueOf(plot.LabelPositionBottom),
		"LabelPositionInside":            reflect.ValueOf(plot.LabelPositionInside),
		"LabelPositionInsideBottom":      reflect.ValueOf(plot.LabelPositionInsideBottom),
		"LabelPositionInsideBottomLeft":  reflect.ValueOf(plot.LabelPositionInsideBottomLeft),
		"LabelPositionInsideBottomRight": reflect.ValueOf(plot.LabelPositionInsideBottomRight),
		"LabelPositionInsideLeft":        reflect.ValueOf(plot.LabelPositionInsideLeft),
		"LabelPositionInsideRight":       reflect.ValueOf(plot.LabelPositionInsideRight),
		"LabelPositionInsideTop":         reflect.ValueOf(plot.LabelPositionInsideTop),
		"LabelPositionInsideTopLeft":     reflect.ValueOf(plot.LabelPositionInsideTopLeft),
		"LabelPositionInsideTopRight":    reflect.ValueOf(plot.LabelPositionInsideTopRight),
		"LabelPositionLeft":              reflect.ValueOf(plot.LabelPositionLeft),
		"LabelPositionRight":             reflect.ValueOf(plot.LabelPositionRight),
		"LabelPositionTop":               reflect.ValueOf(plot.LabelPositionTop),
		"PositionBottom":                 reflect.ValueOf(plot.PositionBottom),
		"PositionLeft":                   reflect.ValueOf(plot.PositionLeft),
		"PositionRight":                  reflect.ValueOf(plot.PositionRight),
		"PositionTop":                    reflect.ValueOf(plot.PositionTop),
		"SaveHTML":                       reflect.ValueOf(plot.SaveHTML),
		"SavePNG":                        reflect.ValueOf(plot.SavePNG),
		"ThemeChalk":                     reflect.ValueOf(plot.ThemeChalk),
		"ThemeEssos":                     reflect.ValueOf(plot.ThemeEssos),
		"ThemeInfographic":               reflect.ValueOf(plot.ThemeInfographic),
		"ThemeMacarons":                  reflect.ValueOf(plot.ThemeMacarons),
		"ThemePurplePassion":             reflect.ValueOf(plot.ThemePurplePassion),
		"ThemeRiverAxisTypeTime":         reflect.ValueOf(plot.ThemeRiverAxisTypeTime),
		"ThemeRoma":                      reflect.ValueOf(plot.ThemeRoma),
		"ThemeRomantic":                  reflect.ValueOf(plot.ThemeRomantic),
		"ThemeShine":                     reflect.ValueOf(plot.ThemeShine),
		"ThemeVintage":                   reflect.ValueOf(plot.ThemeVintage),
		"ThemeWalden":                    reflect.ValueOf(plot.ThemeWalden),
		"ThemeWesteros":                  reflect.ValueOf(plot.ThemeWesteros),
		"ThemeWonderland":                reflect.ValueOf(plot.ThemeWonderland),
		"WordCloudShapeArrow":            reflect.ValueOf(plot.WordCloudShapeArrow),
		"WordCloudShapeCircle":           reflect.ValueOf(plot.WordCloudShapeCircle),
		"WordCloudShapeDiamond":          reflect.ValueOf(plot.WordCloudShapeDiamond),
		"WordCloudShapePin":              reflect.ValueOf(plot.WordCloudShapePin),
		"WordCloudShapeRect":             reflect.ValueOf(plot.WordCloudShapeRect),
		"WordCloudShapeRoundRect":        reflect.ValueOf(plot.WordCloudShapeRoundRect),
		"WordCloudShapeTriangle":         reflect.ValueOf(plot.WordCloudShapeTriangle),

		// type definitions
		"BarChartConfig":        reflect.ValueOf((*plot.BarChartConfig)(nil)),
		"BoxPlotConfig":         reflect.ValueOf((*plot.BoxPlotConfig)(nil)),
		"BoxPlotSeries":         reflect.ValueOf((*plot.BoxPlotSeries)(nil)),
		"FunnelChartConfig":     reflect.ValueOf((*plot.FunnelChartConfig)(nil)),
		"GaugeChartConfig":      reflect.ValueOf((*plot.GaugeChartConfig)(nil)),
		"HeatMapConfig":         reflect.ValueOf((*plot.HeatMapConfig)(nil)),
		"KlineChartConfig":      reflect.ValueOf((*plot.KlineChartConfig)(nil)),
		"KlinePoint":            reflect.ValueOf((*plot.KlinePoint)(nil)),
		"LabelPosition":         reflect.ValueOf((*plot.LabelPosition)(nil)),
		"LineChartConfig":       reflect.ValueOf((*plot.LineChartConfig)(nil)),
		"PieChartConfig":        reflect.ValueOf((*plot.PieChartConfig)(nil)),
		"PieItem":               reflect.ValueOf((*plot.PieItem)(nil)),
		"Position":              reflect.ValueOf((*plot.Position)(nil)),
		"RadarChartConfig":      reflect.ValueOf((*plot.RadarChartConfig)(nil)),
		"RadarSeries":           reflect.ValueOf((*plot.RadarSeries)(nil)),
		"Renderable":            reflect.ValueOf((*plot.Renderable)(nil)),
		"SankeyChartConfig":     reflect.ValueOf((*plot.SankeyChartConfig)(nil)),
		"SankeyLink":            reflect.ValueOf((*plot.SankeyLink)(nil)),
		"ScatterChartConfig":    reflect.ValueOf((*plot.ScatterChartConfig)(nil)),
		"ScatterPoint":          reflect.ValueOf((*plot.ScatterPoint)(nil)),
		"Theme":                 reflect.ValueOf((*plot.Theme)(nil)),
		"ThemeRiverAxisType":    reflect.ValueOf((*plot.ThemeRiverAxisType)(nil)),
		"ThemeRiverChartConfig": reflect.ValueOf((*plot.ThemeRiverChartConfig)(nil)),
		"ThemeRiverData":        reflect.ValueOf((*plot.ThemeRiverData)(nil)),
		"WordCloudConfig":       reflect.ValueOf((*plot.WordCloudConfig)(nil)),
		"WordCloudShape":        reflect.ValueOf((*plot.WordCloudShape)(nil)),

		// interface wrapper definitions
		"_Renderable": reflect.ValueOf((*_github_com_HazelnutParadise_insyra_plot_Renderable)(nil)),
	}
}

// _github_com_HazelnutParadise_insyra_plot_Renderable is an interface wrapper for Renderable type
type _github_com_HazelnutParadise_insyra_plot_Renderable struct {
	IValue         interface{}
	WRender        func(w io.Writer) error
	WRenderContent func() []byte
}

func (W _github_com_HazelnutParadise_insyra_plot_Renderable) Render(w io.Writer) error {
	return W.WRender(w)
}
func (W _github_com_HazelnutParadise_insyra_plot_Renderable) RenderContent() []byte {
	return W.WRenderContent()
}
